plugins {
    id 'com.android.application'
}

android {
    namespace 'org.kernyx.provider'
    compileSdk 36

    defaultConfig {
        applicationId "org.kernyx.provider"
        minSdk 28
        targetSdk 36
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.7.1'
    implementation 'androidx.credentials:credentials:1.3.0'
}
